# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uZErnYnLC5vD1vs7heQkx53HtSdjGh9
"""

# Removed Colab-specific code for local execution
# from google.colab import drive
# drive.mount('/content/drive')

# zip_path = "/content/drive/MyDrive/Colab Notebooks/r4.2.tar.bz2"

# print("Step 1: Extracting files... please wait.")
# import subprocess
# subprocess.run(["tar", "-xjf", zip_path, "-C", "/content/"])
# print("Success! Now you can start training.")

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
import joblib

# 1. Load the data
print("Loading data... please wait.")
# Assuming data files are in the 'data' directory locally
logon = pd.read_csv('data/logon.csv', nrows=500000)
device = pd.read_csv('data/device.csv', nrows=500000)
file_logs = pd.read_csv('data/file.csv', nrows=500000)

print("Creating Behavioral Features...")
# Processing Logon Data
logon['date'] = pd.to_datetime(logon['date'])
logon['hour'] = logon['date'].dt.hour
user_profiles = logon.groupby('user').size().reset_index(name='login_count')

# Feature: Night Logins (Anomaly: working 10PM - 6AM)
night = logon[(logon['hour'] < 6) | (logon['hour'] > 22)].groupby('user').size().reset_index(name='night_logins')
user_profiles = user_profiles.merge(night, on='user', how='left')

# Feature: USB Usage (device.csv HAS an 'activity' column)
usb = device[device['activity'] == 'Connect'].groupby('user').size().reset_index(name='usb_count')
user_profiles = user_profiles.merge(usb, on='user', how='left')

# --- FIXED SECTION ---
# Feature: File Activity (file.csv DOES NOT have an 'activity' column)
# We just count the number of rows per user in this file
files = file_logs.groupby('user').size().reset_index(name='file_activity_count')
user_profiles = user_profiles.merge(files, on='user', how='left')
# ----------------------

# Clean up data
user_profiles = user_profiles.fillna(0)

print("Training Isolation Forest Anomaly Detector...")
# The AI looks for patterns that are 'isolated' from the norm
X = user_profiles[['login_count', 'night_logins', 'usb_count', 'file_activity_count']]
model = IsolationForest(contamination=0.02, random_state=42)
user_profiles['anomaly_label'] = model.fit_predict(X)

# Generate Risk Score (0-100) for your Dashboard
decision_scores = model.decision_function(X)
user_profiles['risk_score'] = np.round((1 - decision_scores) * 100, 2)

print("\n--- PROJECT RESULTS ---")
print("Top Suspicious Users found by AI:")
print(user_profiles.sort_values(by='risk_score', ascending=False).head(10))

# Save the report locally
user_profiles.to_csv('data/final_insider_threat_report.csv', index=False)
joblib.dump(model, 'data/insider_threat_model.pkl')

print("\nSUCCESS: 'final_insider_threat_report.csv' is now in your data directory!")